parameters:
  build_type: ''
  cmake_flags: ''

steps:
  - bash: |
      cd mac-setup
      ./installmacports.sh
      ./cleanmacports.sh
    displayName: 'Install macports'
  - bash: |
      cd mac-setup
      ./build-gettext.sh
      ./build-mac-integration.sh
    displayName: 'Build Gettext and mac-integration'
  - bash: |
      cd mac-setup
      ./complete-build.sh $HOME/gtk
    displayName: 'Build Xournal++'
