parameters:
  build_type: ''
  cmake_flags: ''
  jhbuild_user: 'git-bin'

steps:
  - bash: |
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }}
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} UserShell /bin/bash
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} RealName "Joe Admin"
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} UniqueID "1011"
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} PrimaryGroupID 20
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} NFSHomeDirectory /Users/${{ parameters.jhbuild_user }}
      sudo dscl . -passwd /Users/${{ parameters.jhbuild_user }} password
    displayName: "create new user"
  - bash: |
      cd /Users/${{ parameters.jhbuild_user }}
      sudo -s -u ${{ parameters.jhbuild_user }} curl -L -O https://gitlab.gnome.org/GNOME/gtk-osx/raw/master/gtk-osx-setup.sh
      sudo -s -u ${{ parameters.jhbuild_user }} chmod +x gtk-osx-setup.sh
      sudo -s -u ${{ parameters.jhbuild_user }} sudo ./gtk-osx-setup.sh
      sudo -s -u ${{ parameters.jhbuild_user }} sudo jhbuild bootstrap-gtk-osx
      sudo -s -u ${{ parameters.jhbuild_user }} sudo jhbuild build meta-gtk-osx-bootstrap meta-gtk-osx-gtk3
    displayName: 'Install jhbuild and build gtk+'
  - bash: |
      sudo jhbuild run ./build-poppler.sh
      sudo jhbuild run ./build-portaudio.sh
      sudo jhbuild run ./build-libzip.sh
      sudo jhbuild run ./build-sndfile.sh
      sudo jhbuild run jhbuild build adwaita-icon-theme
    displayName: 'Build Deps'
  - bash: |
      mkdir build
    displayName: 'Create Build Directory'
  - bash: |
      # Ninja >= 1.10.0 binaries depend on Catalina or newer, so use 1.9.0 instead.
      curl -L -o ninja-mac.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip

      # curl -L -o ninja-mac.zip $(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep "browser_download_url.*mac\.zip" | cut -d : -f 2,3 | tr -d '"')
      # Fallback to version 1.9.0 if the previous request fails for some reason
      if [ ! -f ninja-mac.zip ]; then
        curl -L -o ninja-mac.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip
      fi
      unzip ninja-mac.zip -d /Users/git-bin/gtk/inst/bin
    displayName: 'Get Ninja'
  - bash: |
      export PATH="$HOME/.local/bin:/Users/git-bin/gtk/inst/bin:$PATH"
      cmake -GNinja -DCMAKE_INSTALL_PREFIX:PATH=/Users/git-bin/gtk/inst .. -DCMAKE_BUILD_TYPE=${{ parameters.build_type }} ${{ parameters.cmake_flags }}
      # Make sure pot is up to date with sources (maybe translation pipeline is currently running)
      cmake --build . --target pot
      cmake --build . --target translations
      # Build Xournal++
      cmake --build .
      cmake --build . --target install
    workingDirectory: ./build
    displayName: 'Build Xournal++'
