parameters:
  build_type: ''
  cmake_flags: ''
  jhbuild_user: 'git-bin'

steps:
  - bash: |
      sudo mkdir /Users/${{ parameters.jhbuild_user }}
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }}
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} UserShell /bin/bash
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} RealName "gtk-bin"
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} UniqueID "1011"
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} PrimaryGroupID 20
      sudo dscl . -create /Users/${{ parameters.jhbuild_user }} NFSHomeDirectory /Users/${{ parameters.jhbuild_user }}
      sudo dscl . -passwd /Users/${{ parameters.jhbuild_user }} password
      cd /Users/${{ parameters.jhbuild_user }}
      sudo chown -R ${{ parameters.jhbuild_user }}: /Users/${{ parameters.jhbuild_user }}
      sudo -H -i -u ${{ parameters.jhbuild_user }} chmod -R 777 /Users/${{ parameters.jhbuild_user }}
      #echo "${{ parameters.jhbuild_user }}     ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers
    displayName: "create new user"
    timeoutInMinutes: 5
  - bash: |
      whoami
      cd mac-setup
      sudo -H -i -u ${{ parameters.jhbuild_user }} "$PWD"/build-gtk3.sh
    displayName: 'Install jhbuild and build gtk+'
  - bash: |
      cd mac-setup
      sudo -s -u ${{ parameters.jhbuild_user }} jhbuild run ./build-poppler.sh
      sudo -s -u ${{ parameters.jhbuild_user }} jhbuild run ./build-portaudio.sh
      sudo -s -u ${{ parameters.jhbuild_user }} jhbuild run ./build-libzip.sh
      sudo -s -u ${{ parameters.jhbuild_user }} jhbuild run ./build-sndfile.sh
      sudo -s -u ${{ parameters.jhbuild_user }} jhbuild build adwaita-icon-theme
    displayName: 'Build Deps'
  - bash: |
      mkdir build
    displayName: 'Create Build Directory'
  - bash: |
      # Ninja >= 1.10.0 binaries depend on Catalina or newer, so use 1.9.0 instead.
      curl -L -o ninja-mac.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip

      # curl -L -o ninja-mac.zip $(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep "browser_download_url.*mac\.zip" | cut -d : -f 2,3 | tr -d '"')
      # Fallback to version 1.9.0 if the previous request fails for some reason
      if [ ! -f ninja-mac.zip ]; then
        curl -L -o ninja-mac.zip https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip
      fi
      unzip ninja-mac.zip -d /Users/git-bin/gtk/inst/bin
    displayName: 'Get Ninja'
  - bash: |
      export PATH="$HOME/.local/bin:/Users/git-bin/gtk/inst/bin:$PATH"
      cmake -GNinja -DCMAKE_INSTALL_PREFIX:PATH=/Users/git-bin/gtk/inst .. -DCMAKE_BUILD_TYPE=${{ parameters.build_type }} ${{ parameters.cmake_flags }}
      # Make sure pot is up to date with sources (maybe translation pipeline is currently running)
      cmake --build . --target pot
      cmake --build . --target translations
      # Build Xournal++
      cmake --build .
      cmake --build . --target install
    workingDirectory: ./build
    displayName: 'Build Xournal++'
