trigger:
  branches:
    include:
      - '*'
    exclude:
      - stable
      - l10n_master
  paths:
    exclude:
      - po/xournalpp.pot
      - po/*.po


stages:
  - stage: 'Build_Test_Stage'
    jobs:
      - job: macOS
        pool:
          vmImage: 'macOS-10.15'
        displayName: 'Test Xournal++ on MacOS'
        steps:
          - template: steps/build_mac.yml
            parameters:
              build_type: 'Debug'
              cmake_flags: '-DCMAKE_DEBUG_INCLUDES_LDFLAGS=ON -DENABLE_CPPUNIT=ON -DDEBUG_COMPILE=ON'
          - bash: |
              export PATH="$HOME/.local/bin:/Users/git-bin/gtk/inst/bin:$PATH"
              install_name_tool -add_rpath /Users/git-bin/gtk/inst/lib/. test/test-loadHandler
              install_name_tool -add_rpath /Users/git-bin/gtk/inst/lib/. test/test-util
              CI=true ctest --verbose
            workingDirectory: ./build
            displayName: 'Run tests'
